// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClm2Ol84oCb2b2uww0LX9OwdKw2Tu0ZRU',
    appId: '1:529319056665:web:6b66f5fa69184365be2188',
    messagingSenderId: '529319056665',
    projectId: 'healthbody-mind',
    authDomain: 'healthbody-mind.firebaseapp.com',
    storageBucket: 'healthbody-mind.firebasestorage.app',
    measurementId: 'G-437TKRNJNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYa01xh-P06tR_ad7_S6LqzYSkVGJIckY',
    appId: '1:529319056665:android:4099f35a6a576fecbe2188',
    messagingSenderId: '529319056665',
    projectId: 'healthbody-mind',
    storageBucket: 'healthbody-mind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCliDkeFer87iFE89Cr_Vl3DofhJ3bKSwA',
    appId: '1:529319056665:ios:7684b846883ce82bbe2188',
    messagingSenderId: '529319056665',
    projectId: 'healthbody-mind',
    storageBucket: 'healthbody-mind.firebasestorage.app',
    iosBundleId: 'com.example.flutterHbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCliDkeFer87iFE89Cr_Vl3DofhJ3bKSwA',
    appId: '1:529319056665:ios:7684b846883ce82bbe2188',
    messagingSenderId: '529319056665',
    projectId: 'healthbody-mind',
    storageBucket: 'healthbody-mind.firebasestorage.app',
    iosBundleId: 'com.example.flutterHbm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClm2Ol84oCb2b2uww0LX9OwdKw2Tu0ZRU',
    appId: '1:529319056665:web:4b01919d5e5307c9be2188',
    messagingSenderId: '529319056665',
    projectId: 'healthbody-mind',
    authDomain: 'healthbody-mind.firebaseapp.com',
    storageBucket: 'healthbody-mind.firebasestorage.app',
    measurementId: 'G-3YWC22WV47',
  );
}
